language: "php"

php:
    - "5.6"
    - "7.0"

before_install:
    - "composer self-update"

install:
    - "composer install"

script:
    - "php vendor/bin/phpunit --coverage-clover=coverage.clover --coverage-text --verbose"

after_script:
    - "php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover"
