language: "php"

php:
    - "5.4"
    - "5.5"
    - "5.6"

before_install:
    - "composer self-update"

install:
    - "composer install"

script:
    - "php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover"

after_script:
    - "php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover"
