language: "php"

php:
    - "5.4"
    - "5.5"
    - "5.6"
    - "hhvm"

before_install:
    - "composer self-update"

install:
    - "composer install"

script:
    - "php vendor/bin/phpunit --coverage-clover=coverage.clover --coverage-text --verbose"

after_script:
    - "if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi"
